### PR TITLE
Make the IK client optional in the Spot API wrapper

### LINKED ISSUE #280: Inverse Kinematic Client failed to authenticate robot
While running the spot_ros2 driver using a config file, I got the following messages:

```
[kinematic_node-3] [ERROR] [1708810180.621631958] [uml_spot.kinematic_service]: Failed to authenticate robot: Failed to create Inverse Kinematic client.
[kinematic_node-3] terminate called after throwing an instance of 'std::runtime_error'
[kinematic_node-3]   what():  Failed to authenticate robot: Failed to create Inverse Kinematic client.
[ERROR] [kinematic_node-3]: process has died [pid 879722, exit code -6, cmd '/home/jbreen/ros2_ws/install/spot_driver/lib/spot_driver/kinematic_node --ros-args -r __ns:=/uml_spot --params-file /home/jbreen/ros2_ws/spot_config.yaml --params-file /tmp/launch_params_5enosgom'].
[spot_image_publisher_node-2] [ERROR] [1708810180.766739795] [uml_spot.image_publisher]: Failed to authenticate robot: Failed to create Inverse Kinematic client.
[spot_image_publisher_node-2] terminate called after throwing an instance of 'std::runtime_error'
[spot_image_publisher_node-2]   what():  Failed to authenticate robot: Failed to create Inverse Kinematic client.
[ERROR] [spot_image_publisher_node-2]: process has died [pid 879720, exit code -6, cmd '/home/jbreen/ros2_ws/install/spot_driver/lib/spot_driver/spot_image_publisher_node --ros-args -r __ns:=/uml_spot --params-file /home/jbreen/ros2_ws/spot_config.yaml --params-file /tmp/launch_params_j3luh427'].

```

I am using the following command and config file:

```
ros2 launch spot_driver spot_driver.launch.py config_file:=/home/null/ros2_ws/spot_config.yaml spot_name:=uml_spot
```

Here is the config file:

```

/**:
  ros__parameters:
    username: "user"
    password: "exkox2qjjeqx"
    hostname: "192.168.80.3"
    robot_state_rate: 10.0
    metrics_rate: 0.04
    lease_rate: 1.0
    image_rate: 10.0
    auto_claim: False
    auto_power_on: False
    auto_stand: False
    deadzone: 0.05
    estop_timeout: 9.0
    start_estop: False
    preferred_odom_frame: "uml_spot/odom"
    cmd_duration: 0.125
    rgb_cameras: True
    initialize_spot_cam: True
```

I am also running the latest spot_ros2 driver.

### PR DESCRIPTION
**Pull request by jschornak-bdai**
## Change Overview

Spots running firmware older than 3.3.0 cannot initialize the inverse kinematics client through the Spot API. This change makes initializing the IK client optional, which lets the driver nodes that don't need it to launch and run successfully, and in turn allows the driver work for Spots running older firmware versions. This fixes #280.

I also renamed the `kinematicApi` function to `kinematicInterface` to match the pattern used for the other functions in the `SpotApi` class.

## Testing Done

- [ ] Test on a Spot with firmware newer than 3.3.0. Run [this example](https://github.com/bdaiinstitute/spot_ros2/blob/fa36755104fb18d47cae8d18dba6bf316f1c76af/spot_examples/spot_examples/send_inverse_kinematics_requests.py) to test the IK client.
- [ ] Test on a Spot with firmware older than 3.3.0. Make sure the image publisher nodes, etc. launch successfully.

### CODE REVIEW

File: spot_driver/include/spot_driver/api/default_spot_api.hpp [hunk 1]
```diff
@@ -22,15 +23,15 @@ class DefaultSpotApi : public SpotApi {
   tl::expected<void, std::string> createRobot(const std::string& ip_address, const std::string& robot_name) override;
   tl::expected<void, std::string> authenticate(const std::string& username, const std::string& password) override;
   tl::expected<bool, std::string> hasArm() const override;
-  std::shared_ptr<KinematicApi> kinematicApi() const override;
+  std::optional<std::shared_ptr<KinematicApi>> kinematicInterface() const override;
```
Comment (amessing-bdai) [inline spot_driver/include/spot_driver/api/default_spot_api.hpp:26]: Are you using the `nullopt` in a different capacity that `nullptr`?

**Review by tcappellari-bdai — APPROVED** [review]
i agree with Katie - lgtm

File: spot_driver/include/spot_driver/api/default_spot_api.hpp (hunk 1 above)
Comment (jschornak-bdai) [reply spot_driver/include/spot_driver/api/default_spot_api.hpp:26]: I'm sort of on the fence about this still. What I landed on before pushing was that a `nullopt` within a `std::optional` is communicating something different than a `nullptr` within a `std::shared_ptr`, but now I'm leaning towards both of those meaning "this hasn't been initialized yet". I think I'll change it back and just check for `nullptr` when initializing the IK node, since that's a simpler change and a pattern that can be used for the other nodes too.

**Review by khughes-bdai — APPROVED** [review]

**Review by tcappellari-bdai — APPROVED** [review]
